name: frontend-easy-buy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker Imge
    runs-on: ubuntu-latest
    steps:
      - #checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3

      - #Login to Docker Hub using secret in github
        name: Login to docker hub
        uses: docker/login-action/@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - #Create a build kit builder instance
        name: Set up docker Build
        uses: docker/setup-buildx-action@v2

      - #Build the container image and push it to Docker Hub with name frontend-easy-buy
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/frontend-easy-buy:latest

      - #Deploy To VPS
        name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          host: ${{secrets.VPS_IP}}
          username: ${{secrets.VPS_USERNAME}}
          key: ${{secrets.VPS_SSH_KEY}}
          port: 22
        script: |
          cd easy-buy-frontend
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/frontend-easy-buy:latest
          docker-compose up -d --build
