name: frontend-easy-buy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker Imge
    runs-on: ubuntu-latest
    steps:
      - #checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v2

      - #Login to Docker Hub using secret in github
        name: Login to docker hub
        uses: docker/login-action/@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - #Create env
        name: Create .env
        run: |
          touch .env
          echo VITE_API_BASE_URL = ${{secrets.VITE_API_BASE_URL}} >> .env
          echo VITE_NODE_ENV = ${{secrets.VITE_NODE_ENV}} >> .env
          echo VITE_SOCKET_URL = ${{secrets.VITE_SOCKET_URL}} >> .env

      - #Create a build kit builder instance
        name: Set up docker Build
        uses: docker/setup-buildx-action@v2

      - #Build the container image and push it to Docker Hub with name frontend-easy-buy
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/frontend-easy-buy:latest

      - #Deploy To VPS
        name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          username: ${{secrets.VPS_USERNAME}}
          password: ${{secrets.VPS_PASSWORD}}
          script: |
            cd frontend-easy-buy
            curl -o docker-compose.prod.yml https://raw.githubusercontent.com/shirloin/frontend-easy-buy/main/docker-compose.prod.yml
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/frontend-easy-buy:latest
            docker compose -f docker-compose.prod.yml up -d
